development: &common
  enable_logging: yes
  autoload_paths:
    - app/models
    - app/services
  default_timezone: 'Pacific Time (US & Canada)'

test:
  <<: *common
  enable_logging: no

staging:
  <<: *common

production:
  <<: *common
  enable_logging: no
