# Defult database is used by default.
# Any models locating at app/models root directory will point to this database by default.
default:
  development: &common
    adapter: postgresql
    username:
    password:
    database: happy_friday_development
    min_messages: WARNING
    reconnect: true
    pool: 5
    encoding: unicode
    host: localhost

  test:
    <<: *common
    database: happy_friday_test

  production:
    <<: *common
    database: happy_friday_production

second_one:
  development: &common
    adapter: postgresql
    username:
    password:
    database: second_sample_development
    min_messages: WARNING
    reconnect: true
    pool: 5
    encoding: unicode
    host: localhost

  test:
    <<: *common
    database: second_sample_test

  production:
    <<: *common
    database: second_sample_production
