# Defult database is used by default.
# Any models locating at app/models root directory will point to this database by default.
default:
  development: &common
    adapter: postgresql
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    database: happy_friday_development
    min_messages: WARNING
    reconnect: true
    pool: 5
    encoding: unicode
    host: localhost

  test:
    <<: *common
    database: happy_friday_test

  production:
    <<: *common
    database: happy_friday_production
